name: REUSABLE ACTION - Build and Deploy a WAVEMAKER application to AWS Elastic Beanstalk

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.11.0'
      npm-version:
        required: false
        type: string
        default: '10.9.0'
    secrets:
      POSTMAN_API_KEY:
        required: true
      POSTMAN_WORKSPACE_ID:
        required: true
      TARGET_COLLECTION:
        required: true

jobs:
  swagger-to-postman:
    name: Migrate collection from Wavemaker to Postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Use specific npm version
        run: npm i -g npm@${{ inputs.npm-version }}

      - name: Fetch wavemaker to postman javascript files.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          FILE_URL="https://api.github.com/repos/ItalyNewCode/wavemakerApiToPostman/contents/package.json"
          curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o package.json "$FILE_URL"
          echo "Fetched main/package.json file."

          # Fetch the postman-swagger.js  file
          FILE_URL="https://api.github.com/repos/ItalyNewCode/wavemakerApiToPostman/contents/postman-swagger.js"
          curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o postman-swagger.js "$FILE_URL"
          echo "Fetched postman-swagger.js file."

          ls -al

      - name: Install script deps
        run: npm install

      - name: Run migration script
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_TARGET_UID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
          POSTMAN_COLLECTION_NAME: ${{ secrets.TARGET_COLLECTION }}
          POSTMAN_PRUNE: "true"
        run: node postman-swagger.js
