name: REUSABLE ACTION - Build and Deploy a WAVEMAKER application to AWS Elastic Beanstalk

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '22.11.0'
      npm-version:
        required: false
        type: string
        default: '10.9.0'
    secrets:
      POSTMAN_API_KEY:
        required: true
      POSTMAN_WORKSPACE_ID:
        required: true
      TARGET_COLLECTION:
        required: true

jobs:
  swagger-to-postman:
    name: Migrate collection from Wavemaker to Postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}   # checks out the repo that triggered the workflow
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Use specific npm version
        run: npm i -g npm@${{ inputs.npm-version }}

      - name: Fetch wavemaker to postman javascript files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" \
            -o package.json \
            https://api.github.com/repos/ItalyNewCode/wavemakerApiToPostman/contents/package.json

          curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.raw" \
            -o postman-swagger.js \
            https://api.github.com/repos/ItalyNewCode/wavemakerApiToPostman/contents/postman-swagger.js

          ls -al

      - name: Install script deps
        run: npm install

      - name: Run migration script
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_TARGET_UID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
          POSTMAN_COLLECTION_NAME: ${{ secrets.TARGET_COLLECTION }}
          POSTMAN_PRUNE: "true"
        run: node postman-swagger.js